### ISSUE TITLE
Unescaped $ in template string throw unexpected EOF error

### ISSUE THREAD

**Issue by Conduitry** [Rich-Harris/shimport#16]
Trying to transform the following valid javascript

```javascript
let foo = `$`;
```

results in an exception from Shimport. As far as I can tell, the unescaped `$` can appear anywhere in the string and cause this error. If an unescaped `$` in a template string is not followed by a `{`, Shimport should just treat it like a regular character.

**Comment by Rich-Harris** [comment]
Fixed in 0.0.15 — thanks
