### ISSUE TITLE
Feature: URL resolver

### ISSUE THREAD

**Issue by gingur** [Rich-Harris/shimport#24]
First off, great work! I love how the solution converts ESM into an AMD like pattern. This works as a great polyfill, however I intend to use this without feature detection and always use it but with the hope I'd be able to inject my own URL resolver.

The ability to "alias" dependencies or optionally append `.js` to URL's that don't specify an extension would be a great addition to `import` that this polyfill might be able to provide. If you agree, I'd be more than happy to provide a PR.

**Comment by Rich-Harris** [comment]
Hey, sorry for the long-delayed response. Shimport is a polyfill, and as such I don't think it makes sense to add support for non-standard features. The only way it would be legitimate to add an additional resolving step would be if import maps become a thing.

**Comment by jimmywarting** [comment]
just skimmed throgh some issues to look around
I don't need import maps or url resolver but @Rich-Harris  is right the right step forward would be to use something like import maps
