### ISSUE TITLE
web-worker example doesn't work

### ISSUE THREAD

**Issue by VirtualTim** [Rich-Harris/shimport#26]
The web-worker example (https://shimport-demos.surge.sh/web-worker/) no longer works.
The evaluate function: https://github.com/Rich-Harris/shimport/blob/adcc2303e452f26c43c3a2b1a3e3712fbcfe11e8/src/load.ts#L33
uses `document.createElement`, however `document` is obviously not available in a worker.
This causes the promise to be be rejected with: `shimport.js Uncaught (in promise) ReferenceError: document is not defined`.

Edit: looks like 0.0.14 was the last version where this worked.

**Comment by VirtualTim** [comment]
I think swapping `typeof URL !== 'undefined'` https://github.com/Rich-Harris/shimport/blob/adcc2303e452f26c43c3a2b1a3e3712fbcfe11e8/src/load.ts#L34
with `typeof document !== 'undefined'` fixes this, although obviously you don't get the ability to debug the `eval`'d scripts. But better that than not working at all, right?

**Comment by Rich-Harris** [comment]
Only took a year and a bit, but this is fixed in 2.0.3. Thanks!
