### ISSUE TITLE
Change LIL License to another License?

### ISSUE THREAD

**Issue by kbradl16** [Rich-Harris/shimport#28]
I'm really enjoying svelte and I'm trying to get started with sapper but i've run into a snag. I cannot use sapper because of the dependency on `shimport` which has the `LIL` license. 

My company does not allow the use of modules with this license.

Anyways I would very much **love** and **appreciate** it if you could also update this module to MIT (or similar open source license) similarly to sapper https://github.com/sveltejs/sapper/commit/a2204a9d2e714cf352811f91de22f4e04aec38de#diff-9879d6db96fd29134fc802214163b95a

**Comment by Rich-Harris** [comment]
Hey, sorry for the long delayed response. Released 2.0.0 with an MIT license
