### ISSUE TITLE
IE 11 support?

### ISSUE THREAD

**Issue by brownieboy** [Rich-Harris/shimport#4]
I couldn't get it to work at all with IE 11.  Is it supported?   (The readme does say "all browsers", and IE 11 is still supported.)

**Comment by lazyhero** [comment]
same question

**Comment by jdhollander** [comment]
Having tried the demos in IE11, it doesn't work.

I get an exception "Object doesn't support this action". In the source it's at src/index.ts line 11:
`load(new URL(scr.getAttribute('data-main'), document.baseURI));`

IE doesn't support the URL constructor. [https://developer.mozilla.org/en-US/docs/Web/API/URL/URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL)

**Comment by webschik** [comment]
There are several problems:

1. Fetch API, URL, Promise are not supported in IE 11. So, to run the `demos/static-imports` locally I've injected there 

```html
<script src="https://cdn.polyfill.io/v2/polyfill.js?features=default,fetch"></script>
```

2. Transform produces unsupported code (e.g. template strings).

Check the demo `demos/static-imports` and `shimport/src/load.ts:27`.

```
// transform(text, url) returns

__shimport__.define('http://localhost:5000/static-imports/main.js', ['./a.js', './b.js'], function(__import, __exports, a, __dep_1){

a = a.default; 
/*import a from './a.js'*/;
var message = __dep_1.message;
/*import { message } from './b.js'*/;

document.body.innerHTML += `\n\t<p>${a}</p>\n\t<p>${message}</p>\n`;\n});
//# sourceURL=http://localhost:5000/static-imports/main.js"
```

@Rich-Harris, what do you think? Should we fix the `transfrom` function or it's better to use tranfrom + Babel?

**Comment by Rich-Harris** [comment]
Yeah, it's a bring-your-own-polyfill deal, and you would need to be serving modules that have been transpiled to ES5 (apart from `import`/`export`). As long as you're doing that, it works great in IE11. I'll make this clearer in the docs when I'm less busy

**Comment by dimensi** [comment]
@Rich-Harris any news ?

**Comment by Conduitry** [comment]
The readme now has a note about what exactly this library does for you and what it needs to do that.
